### ISSUE TITLE
Docker image failing on AWS

### ISSUE THREAD

**Issue by roncewind** [senzing-garage/docker-sshd#304]
When bringing up the AWS perf stack, I only get the following from the sshd service:

```
chpasswd: (user root) pam_chauthtok() failed, error:
Authentication token manipulation error
chpasswd: (line 1, user root) password not changed
Changing password for root.
/app/docker-entrypoint.sh: line 12: /etc/profile: Permission denied
/app/docker-entrypoint.sh: line 13: /etc/profile: Permission denied
/app/docker-entrypoint.sh: line 14: /etc/profile: Permission denied
sshd: no hostkeys available -- exiting.
```

**Comment by roncewind** [comment]
Looks like this was caused by a change made 06 Jun?

https://github.com/senzing-garage/docker-sshd/blame/64c9873141d71c843008da2c83ba6d67ced8feae/Dockerfile#L133

**Comment by roncewind** [comment]
@docktermj I'm not sure why we changed the user. It seems to have broken the image when run in AWS at least. When running as user 1001, you no longer have permissions to do what's in `/app/docker-entrypoint.sh`

**Comment by docktermj** [comment]
Pull requests:  

- https://github.com/senzing-garage/docker-sshd/pull/305
